name: collectd
version: 0.3.0
slug: collectd
description: >-
  Collectd is a daemon which collects system performance statistics periodically and provides mechanisms to store the values in a variety of ways, for example in RRD files.
arch:
  - amd64
  - aarch64
url: https://github.com/codavs65r/ha-addons/collectd
hassio_role: manager
host_network: true
host_dbus: true
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
uart: true
udev: true
startup: services
options:
  hostname: homeassistant
  graphite_host: localhost
  graphite_prefix: collectd
  graphite-exporter_host: localhost
  graphite-exporter_port: 9109
schema:
  hostname: str
  graphite_host: str
  graphite_prefix: str
  graphite-exporter_host: str
  graphite-exporter_port: int
